<?php
/**
 * LifeTrack: Personal Decision Analyzer
 * SCORECARD — Dynamic Image Generation using PHP GD Library
 * 
 * Demonstrates:
 * - PHP GD Library functions
 * - Dynamic image creation (imagecreatetruecolor)
 * - Drawing shapes (imagefilledrectangle, imagefilledellipse)
 * - Adding text (imagestring, imagettftext if available)
 * - Color allocation (imagecolorallocate)
 * - Image output (imagepng)
 * - String functions for formatting text on image
 */

require_once 'db.php';
require_once 'functions.php';

// ============================================================
// GET ENTRY DATA
// ============================================================
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);

if (!$id) {
    http_response_code(400);
    die('Missing entry ID');
}

$entry = getEntryById($pdo, $id);

if (!$entry) {
    http_response_code(404);
    die('Entry not found');
}

// ============================================================
// CHECK IF GD IS AVAILABLE
// ============================================================
if (!extension_loaded('gd')) {
    // Fallback: render HTML scorecard instead
    $page_title = "Score Card - Entry #" . $id;
    require_once 'includes/header.php';
    ?>
    <div class="page-header">
        <h1>🎨 Daily Score Card</h1>
        <p>PHP GD library is not available. Showing HTML version instead.</p>
    </div>
    
    <div class="card" style="max-width: 500px; margin: 0 auto; text-align: center;">
        <div style="padding: var(--space-xl);">
            <p style="font-size: 0.75rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 2px;">LifeTrack Score Card</p>
            <h2 style="margin: var(--space-md) 0; font-size: 1.3rem;">
                <?php echo ucfirst(htmlspecialchars($entry['name'])); ?>
            </h2>
            <p style="color: var(--text-muted); font-size: 0.85rem;"><?php echo $entry['entry_date']; ?></p>
            
            <div class="score-circle-wrap" style="margin: var(--space-xl) 0;">
                <div class="score-circle" 
                     style="--score-pct: <?php echo $entry['score']; ?>; --score-color: var(--<?php echo strtolower($entry['category']); ?>-primary); width: 180px; height: 180px;">
                    <div class="score-circle-inner" style="width: 150px; height: 150px;">
                        <span class="score-number" style="color: var(--<?php echo strtolower($entry['category']); ?>-primary); font-size: 3rem;">
                            <?php echo $entry['score']; ?>
                        </span>
                        <span class="score-label">out of 100</span>
                    </div>
                </div>
            </div>
            
            <span class="badge badge-<?php echo strtolower($entry['category']); ?>" style="font-size: 1rem; padding: 8px 20px;">
                <?php echo getCategoryIcon($entry['category']) . ' ' . strtoupper($entry['category']); ?>
            </span>
            
            <div style="margin-top: var(--space-xl); display: grid; grid-template-columns: repeat(3, 1fr); gap: var(--space-sm); font-size: 0.8rem; color: var(--text-secondary);">
                <div>😴 <?php echo $entry['sleep_hours']; ?>h</div>
                <div>📚 <?php echo $entry['study_hours']; ?>h</div>
                <div>🏃 <?php echo $entry['exercise_minutes']; ?>m</div>
                <div>🍔 <?php echo $entry['junk_food_count']; ?>x</div>
                <div>💧 <?php echo $entry['water_glasses']; ?></div>
                <div>📱 <?php echo $entry['screen_time']; ?>h</div>
            </div>
            
            <p style="margin-top: var(--space-lg); font-size: 0.7rem; color: var(--text-muted);">
                Generated by LifeTrack — Personal Decision Analyzer
            </p>
        </div>
    </div>
    
    <div style="text-align: center; margin-top: var(--space-lg);">
        <a href="dashboard.php" class="btn btn-secondary">← Back to Dashboard</a>
    </div>
    
    <div class="alert alert-warning" style="margin-top: var(--space-xl);">
        ℹ️ <strong>Note:</strong> To generate actual PNG score card images, enable the PHP GD extension in your php.ini file 
        by uncommenting <code>extension=gd</code>.
    </div>
    <?php
    require_once 'includes/footer.php';
    exit;
}

// ============================================================
// GENERATE SCORECARD IMAGE WITH GD
// ============================================================

// Image dimensions
$width = 600;
$height = 400;

// Create canvas
$image = imagecreatetruecolor($width, $height);

// Enable anti-aliasing
imageantialias($image, true);

// ---- Color Allocation ----
// Background gradient simulation
$bg_dark   = imagecolorallocate($image, 10, 10, 15);      // #0a0a0f
$bg_card   = imagecolorallocate($image, 26, 26, 46);      // #1a1a2e
$white     = imagecolorallocate($image, 232, 232, 240);    // #e8e8f0
$gray      = imagecolorallocate($image, 152, 152, 176);    // #9898b0
$muted     = imagecolorallocate($image, 106, 106, 128);    // #6a6a80
$purple    = imagecolorallocate($image, 139, 92, 246);     // #8b5cf6

// Category-specific colors
switch (strtolower($entry['category'])) {
    case 'healthy':
        $cat_color = imagecolorallocate($image, 16, 185, 129);   // #10b981
        $cat_bg    = imagecolorallocate($image, 10, 40, 30);
        break;
    case 'risky':
        $cat_color = imagecolorallocate($image, 245, 158, 11);   // #f59e0b
        $cat_bg    = imagecolorallocate($image, 40, 30, 10);
        break;
    case 'chaotic':
        $cat_color = imagecolorallocate($image, 239, 68, 68);    // #ef4444
        $cat_bg    = imagecolorallocate($image, 40, 15, 15);
        break;
    default:
        $cat_color = $purple;
        $cat_bg    = imagecolorallocate($image, 25, 20, 40);
}

// ---- Draw Background ----
imagefilledrectangle($image, 0, 0, $width, $height, $bg_dark);

// Decorative gradient band at top
imagefilledrectangle($image, 0, 0, $width, 4, $cat_color);

// Inner card background
imagefilledrectangle($image, 20, 20, $width - 20, $height - 20, $bg_card);

// ---- Add subtle decorative circle ----
$circle_color = imagecolorallocatealpha($image, 139, 92, 246, 110);
imagefilledellipse($image, $width - 80, $height - 80, 200, 200, $circle_color);

// ---- Text Rendering ----
// Header
imagestring($image, 2, 40, 35, "LIFETRACK - DAILY SCORE CARD", $muted);

// Separator line
imageline($image, 40, 55, $width - 40, 55, $muted);

// User name (using strtoupper)
$name_text = strtoupper($entry['name']);
imagestring($image, 5, 40, 70, $name_text, $white);

// Date
imagestring($image, 3, 40, 95, "Date: " . $entry['entry_date'], $gray);

// Large score display
$score_text = $entry['score'] . "/100";
// Draw score large - using built-in fonts (font 5 is largest built-in)
imagestring($image, 5, 40, 140, "SCORE:", $gray);

// Large score number - draw each digit bigger by repeating
$score_str = (string)$entry['score'];
$x_pos = 130;
for ($i = 0; $i < strlen($score_str); $i++) {
    imagestring($image, 5, $x_pos, 135, $score_str[$i], $cat_color);
    $x_pos += 12;
}
imagestring($image, 4, $x_pos + 2, 138, " / 100", $gray);

// Category badge
$category_text = strtoupper($entry['category']);
imagefilledrectangle($image, 40, 175, 40 + (strlen($category_text) * 10) + 20, 200, $cat_bg);
imagestring($image, 4, 50, 180, $category_text, $cat_color);

// ---- Habit Details Section ----
$habits_y = 225;
$col1_x = 40;
$col2_x = 320;

// Column 1
imagestring($image, 3, $col1_x, $habits_y, "Sleep:     " . $entry['sleep_hours'] . " hours", $gray);
imagestring($image, 3, $col1_x, $habits_y + 22, "Study:     " . $entry['study_hours'] . " hours", $gray);
imagestring($image, 3, $col1_x, $habits_y + 44, "Exercise:  " . $entry['exercise_minutes'] . " min", $gray);

// Column 2
imagestring($image, 3, $col2_x, $habits_y, "Junk Food: " . $entry['junk_food_count'] . "x", $gray);
imagestring($image, 3, $col2_x, $habits_y + 22, "Water:     " . $entry['water_glasses'] . " glasses", $gray);
imagestring($image, 3, $col2_x, $habits_y + 44, "Screen:    " . $entry['screen_time'] . " hours", $gray);

// Mood
$mood_text = "Mood: " . ucfirst($entry['mood']);
imagestring($image, 3, $col1_x, $habits_y + 72, $mood_text, $gray);

// ---- Score Bar ----
$bar_y = 340;
$bar_width = $width - 80;
$bar_height = 14;
$bar_fill = ($entry['score'] / 100) * $bar_width;

// Bar background
$bar_bg = imagecolorallocate($image, 35, 35, 55);
imagefilledrectangle($image, 40, $bar_y, 40 + $bar_width, $bar_y + $bar_height, $bar_bg);

// Bar fill
imagefilledrectangle($image, 40, $bar_y, 40 + (int)$bar_fill, $bar_y + $bar_height, $cat_color);

// ---- Footer ----
imagestring($image, 1, 40, $height - 35, "Generated by LifeTrack - Personal Decision Analyzer | " . date('Y-m-d H:i'), $muted);

// ---- Output Image ----
header('Content-Type: image/png');
header('Content-Disposition: inline; filename="scorecard_' . $id . '.png"');
imagepng($image);
imagedestroy($image);
